# -*- coding: utf-8 -*-
"""Tic tac toe_Macoun.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18i0UbQQeNX5A7IXfCDmNfbUNqxuhXj06
"""

def play_game():
    print("Vítejte ve hře Tic Tac Toe pro dva hráče")
    print("Hra je na mřížce 3x3. Hráči se střídají v zadávání pozice, kam umístí svůj hrací kámen (X nebo O).")
    print("Vyhrává hráč, který spojí tři své symboly horizontálně, vertikálně nebo diagonálně.")
    print("Pokud je hrací plocha plná a nikdo nevyhrál, jde o remízu.")
    print(25 * "-")

    player_X = input("Zadejte jméno hráče, který bude hrát za 'X': ")
    player_O = input("Zadejte jméno hráče, který bude hrát za 'O': ")
    # Iniciace hrací plochy a dalších proměnných
    gameBoard = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
    possibleNumbers = [1, 2, 3, 4, 5, 6, 7, 8, 9]
    rows, cols = 3, 3

    def printGameBoard():
        """Funkce pro vykreslení hrací plochy."""
        for x in range(rows):
            print("\n+---+---+---+")
            print("|", end="")
            for y in range(cols):
                print(f" {gameBoard[x][y]} |", end="")
        print("\n+---+---+---+")

    def modifyArray(num, turn):
        """Funkce pro modifikaci hrací plochy na základě tahu."""
        num -= 1
        row, col = divmod(num, 3)
        gameBoard[row][col] = turn

    def checkForWinner():
        """Funkce pro kontrolu vítěze."""
        # Kontrola řádků
        for row in gameBoard:
            if row[0] == row[1] == row[2]:
                return row[0]

        # Kontrola sloupců
        for col in range(3):
            if gameBoard[0][col] == gameBoard[1][col] == gameBoard[2][col]:
                return gameBoard[0][col]

        # Kontrola diagonál
        if gameBoard[0][0] == gameBoard[1][1] == gameBoard[2][2]:
            return gameBoard[0][0]
        if gameBoard[0][2] == gameBoard[1][1] == gameBoard[2][0]:
            return gameBoard[0][2]

        return None

    # Herní smyčka
    while True:
        printGameBoard()
        currentPlayer = 'X' if len(possibleNumbers) % 2 == 1 else 'O'
        currentPlayerName = player_X if currentPlayer == 'X' else player_O
        print(f"\n{currentPlayerName} ({currentPlayer}), vyberte číslo [1-9]:")
        try:
            numberPicked = int(input())
            if numberPicked not in possibleNumbers:
                print("Tato pozice je jiz obsazena nebo neexistuje. Zkuste to znovu.")
                continue
        except ValueError:
            print("Zadali jste neplatny vstup. Zkuste to znovu.")
            continue

        modifyArray(numberPicked, currentPlayer)
        possibleNumbers.remove(numberPicked)

        winner = checkForWinner()
        if winner:
            printGameBoard()
            winnerName = player_X if winner == 'X' else player_O
            print(f"\nHrac {winnerName} ({winner}) vyhrava! Gratulujeme!")
            break

        if not possibleNumbers:
            printGameBoard()
            print("\nRemiza! Hraci plocha je plna.")
            break

    print("\nKonec hry! Dekujeme za hrani.")

while True:
    play_game()
    restart = input("Chcete si zahrat znovu? (ano/ne): ").strip().lower()
    if restart != "ano":
        print("Děkujeme za hraní! Nashledanou.")
        break